//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ButtonBarsControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ButtonBarsControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Bar.
        /// </summary>
        internal static string BAR_TEXT {
            get {
                return ResourceManager.GetString("BAR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ok.
        /// </summary>
        internal static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked Button.
        /// </summary>
        internal static string CLICKED_TEXT {
            get {
                return ResourceManager.GetString("CLICKED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Button.
        /// </summary>
        internal static string DISABLED_TEXT {
            get {
                return ResourceManager.GetString("DISABLED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance Editor.
        /// </summary>
        internal static string FORM_TEXT {
            get {
                return ResourceManager.GetString("FORM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovered Button.
        /// </summary>
        internal static string HOVERED_TEXT {
            get {
                return ResourceManager.GetString("HOVERED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available themes.
        /// </summary>
        internal static string LBL_AVAILABLE_THEME {
            get {
                return ResourceManager.GetString("LBL_AVAILABLE_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Style.
        /// </summary>
        internal static string LBL_CURRENT_STYLE {
            get {
                return ResourceManager.GetString("LBL_CURRENT_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string LBL_PREVIEW {
            get {
                return ResourceManager.GetString("LBL_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Apply to current Theme.
        /// </summary>
        internal static string LNK_APPLYTHEME {
            get {
                return ResourceManager.GetString("LNK_APPLYTHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load Theme.
        /// </summary>
        internal static string LNK_LOAD {
            get {
                return ResourceManager.GetString("LNK_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;load.
        /// </summary>
        internal static string LNK_RELOAD {
            get {
                return ResourceManager.GetString("LNK_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string LNK_RESET {
            get {
                return ResourceManager.GetString("LNK_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Theme.
        /// </summary>
        internal static string LNK_SAVETHEME {
            get {
                return ResourceManager.GetString("LNK_SAVETHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Button.
        /// </summary>
        internal static string NORMAL_TEXT {
            get {
                return ResourceManager.GetString("NORMAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Hover.
        /// </summary>
        internal static string SELECTED_HOVER_TEXT {
            get {
                return ResourceManager.GetString("SELECTED_HOVER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Button.
        /// </summary>
        internal static string SELECTED_TEXT {
            get {
                return ResourceManager.GetString("SELECTED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Appearence.
        /// </summary>
        internal static string TAB_BAR {
            get {
                return ResourceManager.GetString("TAB_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Appearence.
        /// </summary>
        internal static string TAB_ITEMS {
            get {
                return ResourceManager.GetString("TAB_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string THEME_BLUE {
            get {
                return ResourceManager.GetString("THEME_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string THEME_CLASSIC {
            get {
                return ResourceManager.GetString("THEME_CLASSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OliveGreen.
        /// </summary>
        internal static string THEME_OLIVE {
            get {
                return ResourceManager.GetString("THEME_OLIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royale.
        /// </summary>
        internal static string THEME_ROYAL {
            get {
                return ResourceManager.GetString("THEME_ROYAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string THEME_SILVER {
            get {
                return ResourceManager.GetString("THEME_SILVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS2005.
        /// </summary>
        internal static string THEME_VS2005 {
            get {
                return ResourceManager.GetString("THEME_VS2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File (*.xml)|*.xml.
        /// </summary>
        internal static string XML_FILE {
            get {
                return ResourceManager.GetString("XML_FILE", resourceCulture);
            }
        }
    }
}
